package net.minecraft.src;

public class ModelScaffold extends ModelBase
{
  //fields
    ModelRenderer BottomFront;
    ModelRenderer BottomBack;
    ModelRenderer BottomRight;
    ModelRenderer BottomLeft;
    ModelRenderer StlitFR;
    ModelRenderer StlitBR;
    ModelRenderer StlitFL;
    ModelRenderer StlitBL;
    ModelRenderer Top;
    ModelRenderer CrossPiece1;
    ModelRenderer CrossPiece2;
    ModelRenderer CrossPiece3;
    ModelRenderer CrossPiece4;
    ModelRenderer CrossPiece5;
    ModelRenderer CrossPiece6;
    ModelRenderer CrossPiece7;
    ModelRenderer CrossPiece8;
    ModelRenderer CrossPiece9;
    ModelRenderer CrossPiece10;
    ModelRenderer CrossPiece11;
    ModelRenderer CrossPiece12;
    ModelRenderer CrossPiece13;
    ModelRenderer CrossPiece14;
    ModelRenderer CrossPiece15;
    ModelRenderer CrossPiece16;
    ModelRenderer CrossPiece17;
    ModelRenderer CrossPiece18;
    ModelRenderer CrossPiece19;
    ModelRenderer CrossPiece20;
    ModelRenderer CrossPiece21;
    ModelRenderer CrossPiece22;
    ModelRenderer CrossPiece23;
    ModelRenderer CrossPiece24;
    ModelRenderer CrossPiece25;
    ModelRenderer CrossPiece26;
    ModelRenderer CrossPiece27;
    ModelRenderer CrossPiece28;
    ModelRenderer StepFront1;
    ModelRenderer StepFront2;
    ModelRenderer StepBack1;
    ModelRenderer StepBack2;
    ModelRenderer StepRight1;
    ModelRenderer StepRight2;
    ModelRenderer StepLeft1;
    ModelRenderer StepLeft2;
  
  public ModelScaffold()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      BottomFront = new ModelRenderer(this, 0, 0);
      BottomFront.addBox(0F, 0F, 0F, 14, 1, 1);
      BottomFront.setRotationPoint(-7F, 23F, -8F);
      BottomFront.setTextureSize(64, 32);
      BottomFront.mirror = true;
      setRotation(BottomFront, 0F, 0F, 0F);
      BottomBack = new ModelRenderer(this, 0, 0);
      BottomBack.addBox(0F, 0F, 0F, 14, 1, 1);
      BottomBack.setRotationPoint(-7F, 23F, 7F);
      BottomBack.setTextureSize(64, 32);
      BottomBack.mirror = true;
      setRotation(BottomBack, 0F, 0F, 0F);
      BottomRight = new ModelRenderer(this, 0, 2);
      BottomRight.addBox(0F, 0F, 0F, 1, 1, 14);
      BottomRight.setRotationPoint(-8F, 23F, -7F);
      BottomRight.setTextureSize(64, 32);
      BottomRight.mirror = true;
      setRotation(BottomRight, 0F, 0F, 0F);
      BottomLeft = new ModelRenderer(this, 0, 2);
      BottomLeft.addBox(0F, 0F, 0F, 1, 1, 14);
      BottomLeft.setRotationPoint(7F, 23F, -7F);
      BottomLeft.setTextureSize(64, 32);
      BottomLeft.mirror = true;
      setRotation(BottomLeft, 0F, 0F, 0F);
      StlitFR = new ModelRenderer(this, 0, 17);
      StlitFR.addBox(0F, 0F, 0F, 1, 15, 1);
      StlitFR.setRotationPoint(-8F, 9F, -8F);
      StlitFR.setTextureSize(64, 32);
      StlitFR.mirror = true;
      setRotation(StlitFR, 0F, 0F, 0F);
      StlitBR = new ModelRenderer(this, 0, 17);
      StlitBR.addBox(0F, 0F, 0F, 1, 15, 1);
      StlitBR.setRotationPoint(-8F, 9F, 7F);
      StlitBR.setTextureSize(64, 32);
      StlitBR.mirror = true;
      setRotation(StlitBR, 0F, 0F, 0F);
      StlitFL = new ModelRenderer(this, 0, 17);
      StlitFL.addBox(0F, 0F, 0F, 1, 15, 1);
      StlitFL.setRotationPoint(7F, 9F, -8F);
      StlitFL.setTextureSize(64, 32);
      StlitFL.mirror = true;
      setRotation(StlitFL, 0F, 0F, 0F);
      StlitBL = new ModelRenderer(this, 0, 17);
      StlitBL.addBox(0F, 0F, 0F, 1, 15, 1);
      StlitBL.setRotationPoint(7F, 9F, 7F);
      StlitBL.setTextureSize(64, 32);
      StlitBL.mirror = true;
      setRotation(StlitBL, 0F, 0F, 0F);
      Top = new ModelRenderer(this, 0, 33);
      Top.addBox(0F, 0F, 0F, 16, 1, 16);
      Top.setRotationPoint(-8F, 8F, -8F);
      Top.setTextureSize(64, 32);
      Top.mirror = true;
      setRotation(Top, 0F, 0F, 0F);
      CrossPiece1 = new ModelRenderer(this, 4, 17);
      CrossPiece1.addBox(0F, 0F, 0F, 1, 1, 1);
      CrossPiece1.setRotationPoint(-7F, 9F, -7F);
      CrossPiece1.setTextureSize(64, 32);
      CrossPiece1.mirror = true;
      setRotation(CrossPiece1, 0F, 0F, 0F);
      CrossPiece2 = new ModelRenderer(this, 4, 17);
      CrossPiece2.addBox(0F, 0F, 0F, 1, 1, 1);
      CrossPiece2.setRotationPoint(-6F, 10F, -6F);
      CrossPiece2.setTextureSize(64, 32);
      CrossPiece2.mirror = true;
      setRotation(CrossPiece2, 0F, 0F, 0F);
      CrossPiece3 = new ModelRenderer(this, 4, 17);
      CrossPiece3.addBox(0F, 0F, 0F, 1, 1, 1);
      CrossPiece3.setRotationPoint(-5F, 11F, -5F);
      CrossPiece3.setTextureSize(64, 32);
      CrossPiece3.mirror = true;
      setRotation(CrossPiece3, 0F, 0F, 0F);
      CrossPiece4 = new ModelRenderer(this, 4, 17);
      CrossPiece4.addBox(0F, 0F, 0F, 1, 1, 1);
      CrossPiece4.setRotationPoint(-4F, 12F, -4F);
      CrossPiece4.setTextureSize(64, 32);
      CrossPiece4.mirror = true;
      setRotation(CrossPiece4, 0F, 0F, 0F);
      CrossPiece5 = new ModelRenderer(this, 4, 17);
      CrossPiece5.addBox(0F, 0F, 0F, 1, 1, 1);
      CrossPiece5.setRotationPoint(-3F, 13F, -3F);
      CrossPiece5.setTextureSize(64, 32);
      CrossPiece5.mirror = true;
      setRotation(CrossPiece5, 0F, 0F, 0F);
      CrossPiece6 = new ModelRenderer(this, 4, 17);
      CrossPiece6.addBox(0F, 0F, 0F, 1, 1, 1);
      CrossPiece6.setRotationPoint(-2F, 14F, -2F);
      CrossPiece6.setTextureSize(64, 32);
      CrossPiece6.mirror = true;
      setRotation(CrossPiece6, 0F, 0F, 0F);
      CrossPiece7 = new ModelRenderer(this, 4, 17);
      CrossPiece7.addBox(0F, 0F, 0F, 1, 1, 1);
      CrossPiece7.setRotationPoint(-1F, 15F, -1F);
      CrossPiece7.setTextureSize(64, 32);
      CrossPiece7.mirror = true;
      setRotation(CrossPiece7, 0F, 0F, 0F);
      CrossPiece8 = new ModelRenderer(this, 4, 17);
      CrossPiece8.addBox(0F, 0F, 0F, 1, 1, 1);
      CrossPiece8.setRotationPoint(0F, 16F, 0F);
      CrossPiece8.setTextureSize(64, 32);
      CrossPiece8.mirror = true;
      setRotation(CrossPiece8, 0F, 0F, 0F);
      CrossPiece9 = new ModelRenderer(this, 4, 17);
      CrossPiece9.addBox(0F, 0F, 0F, 1, 1, 1);
      CrossPiece9.setRotationPoint(1F, 17F, 1F);
      CrossPiece9.setTextureSize(64, 32);
      CrossPiece9.mirror = true;
      setRotation(CrossPiece9, 0F, 0F, 0F);
      CrossPiece10 = new ModelRenderer(this, 4, 17);
      CrossPiece10.addBox(0F, 0F, 0F, 1, 1, 1);
      CrossPiece10.setRotationPoint(2F, 18F, 2F);
      CrossPiece10.setTextureSize(64, 32);
      CrossPiece10.mirror = true;
      setRotation(CrossPiece10, 0F, 0F, 0F);
      CrossPiece11 = new ModelRenderer(this, 4, 17);
      CrossPiece11.addBox(0F, 0F, 0F, 1, 1, 1);
      CrossPiece11.setRotationPoint(3F, 19F, 3F);
      CrossPiece11.setTextureSize(64, 32);
      CrossPiece11.mirror = true;
      setRotation(CrossPiece11, 0F, 0F, 0F);
      CrossPiece12 = new ModelRenderer(this, 4, 17);
      CrossPiece12.addBox(0F, 0F, 0F, 1, 1, 1);
      CrossPiece12.setRotationPoint(4F, 20F, 4F);
      CrossPiece12.setTextureSize(64, 32);
      CrossPiece12.mirror = true;
      setRotation(CrossPiece12, 0F, 0F, 0F);
      CrossPiece13 = new ModelRenderer(this, 4, 17);
      CrossPiece13.addBox(0F, 0F, 0F, 1, 1, 1);
      CrossPiece13.setRotationPoint(5F, 21F, 5F);
      CrossPiece13.setTextureSize(64, 32);
      CrossPiece13.mirror = true;
      setRotation(CrossPiece13, 0F, 0F, 0F);
      CrossPiece14 = new ModelRenderer(this, 4, 17);
      CrossPiece14.addBox(0F, 0F, 0F, 1, 1, 1);
      CrossPiece14.setRotationPoint(6F, 22F, 6F);
      CrossPiece14.setTextureSize(64, 32);
      CrossPiece14.mirror = true;
      setRotation(CrossPiece14, 0F, 0F, 0F);
      CrossPiece15 = new ModelRenderer(this, 4, 17);
      CrossPiece15.addBox(0F, 0F, 0F, 1, 1, 1);
      CrossPiece15.setRotationPoint(6F, 9F, 6F);
      CrossPiece15.setTextureSize(64, 32);
      CrossPiece15.mirror = true;
      setRotation(CrossPiece15, 0F, 0F, 0F);
      CrossPiece16 = new ModelRenderer(this, 4, 17);
      CrossPiece16.addBox(0F, 0F, 0F, 1, 1, 1);
      CrossPiece16.setRotationPoint(5F, 10F, 5F);
      CrossPiece16.setTextureSize(64, 32);
      CrossPiece16.mirror = true;
      setRotation(CrossPiece16, 0F, 0F, 0F);
      CrossPiece17 = new ModelRenderer(this, 4, 17);
      CrossPiece17.addBox(0F, 0F, 0F, 1, 1, 1);
      CrossPiece17.setRotationPoint(4F, 11F, 4F);
      CrossPiece17.setTextureSize(64, 32);
      CrossPiece17.mirror = true;
      setRotation(CrossPiece17, 0F, 0F, 0F);
      CrossPiece18 = new ModelRenderer(this, 4, 17);
      CrossPiece18.addBox(0F, 0F, 0F, 1, 1, 1);
      CrossPiece18.setRotationPoint(3F, 12F, 3F);
      CrossPiece18.setTextureSize(64, 32);
      CrossPiece18.mirror = true;
      setRotation(CrossPiece18, 0F, 0F, 0F);
      CrossPiece19 = new ModelRenderer(this, 4, 17);
      CrossPiece19.addBox(0F, 0F, 0F, 1, 1, 1);
      CrossPiece19.setRotationPoint(2F, 13F, 2F);
      CrossPiece19.setTextureSize(64, 32);
      CrossPiece19.mirror = true;
      setRotation(CrossPiece19, 0F, 0F, 0F);
      CrossPiece20 = new ModelRenderer(this, 4, 17);
      CrossPiece20.addBox(0F, 0F, 0F, 1, 1, 1);
      CrossPiece20.setRotationPoint(1F, 14F, 1F);
      CrossPiece20.setTextureSize(64, 32);
      CrossPiece20.mirror = true;
      setRotation(CrossPiece20, 0F, 0F, 0F);
      CrossPiece21 = new ModelRenderer(this, 4, 17);
      CrossPiece21.addBox(0F, 0F, 0F, 1, 1, 1);
      CrossPiece21.setRotationPoint(0F, 15F, 0F);
      CrossPiece21.setTextureSize(64, 32);
      CrossPiece21.mirror = true;
      setRotation(CrossPiece21, 0F, 0F, 0F);
      CrossPiece22 = new ModelRenderer(this, 4, 17);
      CrossPiece22.addBox(0F, 0F, 0F, 1, 1, 1);
      CrossPiece22.setRotationPoint(-1F, 16F, -1F);
      CrossPiece22.setTextureSize(64, 32);
      CrossPiece22.mirror = true;
      setRotation(CrossPiece22, 0F, 0F, 0F);
      CrossPiece23 = new ModelRenderer(this, 4, 17);
      CrossPiece23.addBox(0F, 0F, 0F, 1, 1, 1);
      CrossPiece23.setRotationPoint(-2F, 17F, -2F);
      CrossPiece23.setTextureSize(64, 32);
      CrossPiece23.mirror = true;
      setRotation(CrossPiece23, 0F, 0F, 0F);
      CrossPiece24 = new ModelRenderer(this, 4, 17);
      CrossPiece24.addBox(0F, 0F, 0F, 1, 1, 1);
      CrossPiece24.setRotationPoint(-3F, 18F, -3F);
      CrossPiece24.setTextureSize(64, 32);
      CrossPiece24.mirror = true;
      setRotation(CrossPiece24, 0F, 0F, 0F);
      CrossPiece25 = new ModelRenderer(this, 4, 17);
      CrossPiece25.addBox(0F, 0F, 0F, 1, 1, 1);
      CrossPiece25.setRotationPoint(-4F, 19F, -4F);
      CrossPiece25.setTextureSize(64, 32);
      CrossPiece25.mirror = true;
      setRotation(CrossPiece25, 0F, 0F, 0F);
      CrossPiece26 = new ModelRenderer(this, 4, 17);
      CrossPiece26.addBox(0F, 0F, 0F, 1, 1, 1);
      CrossPiece26.setRotationPoint(-5F, 20F, -5F);
      CrossPiece26.setTextureSize(64, 32);
      CrossPiece26.mirror = true;
      setRotation(CrossPiece26, 0F, 0F, 0F);
      CrossPiece27 = new ModelRenderer(this, 4, 17);
      CrossPiece27.addBox(0F, 0F, 0F, 1, 1, 1);
      CrossPiece27.setRotationPoint(-6F, 21F, -6F);
      CrossPiece27.setTextureSize(64, 32);
      CrossPiece27.mirror = true;
      setRotation(CrossPiece27, 0F, 0F, 0F);
      CrossPiece28 = new ModelRenderer(this, 4, 17);
      CrossPiece28.addBox(0F, 0F, 0F, 1, 1, 1);
      CrossPiece28.setRotationPoint(-7F, 22F, -7F);
      CrossPiece28.setTextureSize(64, 32);
      CrossPiece28.mirror = true;
      setRotation(CrossPiece28, 0F, 0F, 0F);
      StepFront1 = new ModelRenderer(this, 4, 19);
      StepFront1.addBox(0F, 0F, 0F, 14, 1, 1);
      StepFront1.setRotationPoint(-7F, 13F, -8F);
      StepFront1.setTextureSize(64, 64);
      StepFront1.mirror = true;
      setRotation(StepFront1, 0F, 0F, 0F);
      StepFront2 = new ModelRenderer(this, 4, 19);
      StepFront2.addBox(0F, 0F, 0F, 14, 1, 1);
      StepFront2.setRotationPoint(-7F, 18F, -8F);
      StepFront2.setTextureSize(64, 64);
      StepFront2.mirror = true;
      setRotation(StepFront2, 0F, 0F, 0F);
      StepBack1 = new ModelRenderer(this, 4, 19);
      StepBack1.addBox(0F, 0F, 0F, 14, 1, 1);
      StepBack1.setRotationPoint(-7F, 13F, 7F);
      StepBack1.setTextureSize(64, 64);
      StepBack1.mirror = true;
      setRotation(StepBack1, 0F, 0F, 0F);
      StepBack2 = new ModelRenderer(this, 4, 19);
      StepBack2.addBox(0F, 0F, 0F, 14, 1, 1);
      StepBack2.setRotationPoint(-7F, 18F, 7F);
      StepBack2.setTextureSize(64, 64);
      StepBack2.mirror = true;
      setRotation(StepBack2, 0F, 0F, 0F);
      StepRight1 = new ModelRenderer(this, 30, 0);
      StepRight1.addBox(0F, 0F, 0F, 1, 1, 14);
      StepRight1.setRotationPoint(-8F, 13F, -7F);
      StepRight1.setTextureSize(64, 64);
      StepRight1.mirror = true;
      setRotation(StepRight1, 0F, 0F, 0F);
      StepRight2 = new ModelRenderer(this, 30, 0);
      StepRight2.addBox(0F, 0F, 0F, 1, 1, 14);
      StepRight2.setRotationPoint(-8F, 18F, -7F);
      StepRight2.setTextureSize(64, 64);
      StepRight2.mirror = true;
      setRotation(StepRight2, 0F, 0F, 0F);
      StepLeft1 = new ModelRenderer(this, 30, 0);
      StepLeft1.addBox(0F, 0F, 0F, 1, 1, 14);
      StepLeft1.setRotationPoint(7F, 13F, -7F);
      StepLeft1.setTextureSize(64, 64);
      StepLeft1.mirror = true;
      setRotation(StepLeft1, 0F, 0F, 0F);
      StepLeft2 = new ModelRenderer(this, 30, 0);
      StepLeft2.addBox(0F, 0F, 0F, 1, 1, 14);
      StepLeft2.setRotationPoint(7F, 18F, -7F);
      StepLeft2.setTextureSize(64, 64);
      StepLeft2.mirror = true;
      setRotation(StepLeft2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    BottomFront.render(f5);
    BottomBack.render(f5);
    BottomRight.render(f5);
    BottomLeft.render(f5);
    StlitFR.render(f5);
    StlitBR.render(f5);
    StlitFL.render(f5);
    StlitBL.render(f5);
    Top.render(f5);
    CrossPiece1.render(f5);
    CrossPiece2.render(f5);
    CrossPiece3.render(f5);
    CrossPiece4.render(f5);
    CrossPiece5.render(f5);
    CrossPiece6.render(f5);
    CrossPiece7.render(f5);
    CrossPiece8.render(f5);
    CrossPiece9.render(f5);
    CrossPiece10.render(f5);
    CrossPiece11.render(f5);
    CrossPiece12.render(f5);
    CrossPiece13.render(f5);
    CrossPiece14.render(f5);
    CrossPiece15.render(f5);
    CrossPiece16.render(f5);
    CrossPiece17.render(f5);
    CrossPiece18.render(f5);
    CrossPiece19.render(f5);
    CrossPiece20.render(f5);
    CrossPiece21.render(f5);
    CrossPiece22.render(f5);
    CrossPiece23.render(f5);
    CrossPiece24.render(f5);
    CrossPiece25.render(f5);
    CrossPiece26.render(f5);
    CrossPiece27.render(f5);
    CrossPiece28.render(f5);
    StepFront1.render(f5);
    StepFront2.render(f5);
    StepBack1.render(f5);
    StepBack2.render(f5);
    StepRight1.render(f5);
    StepRight2.render(f5);
    StepLeft1.render(f5);
    StepLeft2.render(f5);
  }
  
  public void renderModel (float f5)
  {
    BottomFront.render(f5);
    BottomBack.render(f5);
    BottomRight.render(f5);
    BottomLeft.render(f5);
    StlitFR.render(f5);
    StlitBR.render(f5);
    StlitFL.render(f5);
    StlitBL.render(f5);
    Top.render(f5);
    CrossPiece1.render(f5);
    CrossPiece2.render(f5);
    CrossPiece3.render(f5);
    CrossPiece4.render(f5);
    CrossPiece5.render(f5);
    CrossPiece6.render(f5);
    CrossPiece7.render(f5);
    CrossPiece8.render(f5);
    CrossPiece9.render(f5);
    CrossPiece10.render(f5);
    CrossPiece11.render(f5);
    CrossPiece12.render(f5);
    CrossPiece13.render(f5);
    CrossPiece14.render(f5);
    CrossPiece15.render(f5);
    CrossPiece16.render(f5);
    CrossPiece17.render(f5);
    CrossPiece18.render(f5);
    CrossPiece19.render(f5);
    CrossPiece20.render(f5);
    CrossPiece21.render(f5);
    CrossPiece22.render(f5);
    CrossPiece23.render(f5);
    CrossPiece24.render(f5);
    CrossPiece25.render(f5);
    CrossPiece26.render(f5);
    CrossPiece27.render(f5);
    CrossPiece28.render(f5);
    StepFront1.render(f5);
    StepFront2.render(f5);
    StepBack1.render(f5);
    StepBack2.render(f5);
    StepRight1.render(f5);
    StepRight2.render(f5);
    StepLeft1.render(f5);
    StepLeft2.render(f5);
  }
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
}
